#!/bin/bash

popaclarity_appname="$1"

if [ -z $popaclarity_appname ]; then popaclarity_appname="App"; fi

git init
git submodule add https://github.com/YonisSavary/Clarity
git submodule add https://github.com/YonisSavary/ClarityPlugins
cp -r Clarity/Server/* .

php craft create-config
php craft create-app --name="$popaclarity_appname"
php craft enable-app ClarityPlugins/AssetsKit

echo "/Storage" >> .gitignore
echo "clarity.json" >> .gitignore